### ISSUE TITLE
snakemake workflow setup

### ISSUE THREAD

**Issue by alisamatisse** [tris-10/MHC_RSE_HiFi_Assembly_Pipeline#1]
Hi, 

Sorry for this question, but what version of Snakemake and Amos do you use for your pipeline? Because for now I see they are not compatible with each other, as Amos required python 3.6 for me. 

Thanks! 
Alisa

**Comment by tmbrgr** [comment]
I don't think it is possible to install all of the required tools into the same environment due to compatibility issues.  The pipeline uses multiple conda environments to get around this issue and when you launch the pipeline, it should create the environments for you and install the software automatically, which are isolated from your main environment. We used Amos 3.1.0 with python 2.7.  The yaml files in the envs/ directory contain all of the software versions if you are curious.  The Snakemake version was 7.24.0

**Comment by alisamatisse** [comment]
Sorry and thanks for the quick reply!

**Comment by alisamatisse** [comment]
just to make it very clear now --- my actual issue was that micromamba did not work with this :/ only conda. thanks!
